import pytest
from aegis.engine import PolicyEngine
from aegis.exceptions import PolicyViolationError
from aegis.core import guardrail

def test_sql_injection_interception():
    engine = PolicyEngine()
    
    # Real dangerous SQL payload generated by hallucinating agent
    malicious_query = "DROP TABLE users; SELECT * FROM logs;"
    result = engine.evaluate("db_query", {"query": malicious_query})
    
    assert result.is_allowed is False
    assert result.triggered_rule == "block_destructive_sql"

def test_shell_command_execution_blocked():
    engine = PolicyEngine()
    
    # Dangerous system destruction attempt
    payload = {"command": "rm -rf /var/www/html"}
    result = engine.evaluate("run_shell", payload)
    
    assert result.is_allowed is False
    assert result.triggered_rule == "block_destructive_shell"

def test_real_secret_redaction():
    engine = PolicyEngine()
    
    # Real AWS key structure test
    payload = {"api_key": "AKIAIOSFODNN7EXAMPLE", "message": "Deploying build"}
    result = engine.evaluate("deploy_cloud", payload)
    
    assert result.is_allowed is True
    assert result.sanitized_args["api_key"] == "[REDACTED_AWS_ACCESS_KEY]"